import 'package:flutter/material.dart';

import 'models.dart';

List<LyricLine> _lyrics(List<String> lines) => List<LyricLine>.generate(
      lines.length,
      (index) => LyricLine(Duration(milliseconds: 700 + index * 1450), lines[index]),
    );

final List<Track> demoTracks = <Track>[
  Track(
    id: 'weightless',
    title: 'Weightless',
    artist: 'Paper Radio',
    album: 'Gluk Sessions · Vol. 001',
    assetPath: 'assets/audio/weightless.wav',
    duration: const Duration(seconds: 14),
    palette: const <Color>[Color(0xFF29323A), Color(0xFF927C67), Color(0xFFE4D7C6)],
    source: TrackSource.gluk,
    moods: const <String>['спокойно', 'ночь', 'выдохнуть'],
    lyrics: _lyrics(const <String>[
      'мир стал чуть тише',
      'и музыка осталась рядом',
      'не торопись',
      'это твоя волна',
      'ещё немного воздуха',
      'и всё встанет на место',
      'мы никуда не спешим',
      'просто слушай',
    ]),
  ),
  Track(
    id: 'afterglow',
    title: 'Afterglow',
    artist: 'Mellow North',
    album: 'Late Light',
    assetPath: 'assets/audio/afterglow.wav',
    duration: const Duration(seconds: 14),
    palette: const <Color>[Color(0xFF4A3D38), Color(0xFFBA8F75), Color(0xFFF0D9B9)],
    source: TrackSource.soundcloud,
    moods: const <String>['тепло', 'вечер', 'медленно'],
    lyrics: _lyrics(const <String>[
      'после света',
      'остаётся тёплый след',
      'он медленно плывёт',
      'по комнате',
      'не выключай его',
      'пока звучит эта песня',
      'ещё один круг',
      'и домой',
    ]),
  ),
  Track(
    id: 'soft-focus',
    title: 'Soft Focus',
    artist: 'Distant Rooms',
    album: 'Window Seat',
    assetPath: 'assets/audio/soft_focus.wav',
    duration: const Duration(seconds: 14),
    palette: const <Color>[Color(0xFF4A5147), Color(0xFF9BA890), Color(0xFFDCE2CF)],
    source: TrackSource.spotify,
    moods: const <String>['фокус', 'работа', 'спокойно'],
    lyrics: _lyrics(const <String>[
      'фокус мягче',
      'шума меньше',
      'одна задача',
      'один ритм',
      'ещё немного',
      'и поток пойман',
      'оставь остальное',
      'на потом',
    ]),
  ),
  Track(
    id: 'night-bus',
    title: 'Night Bus',
    artist: 'Neon Courier',
    album: 'City After 01:00',
    assetPath: 'assets/audio/night_bus.wav',
    duration: const Duration(seconds: 14),
    palette: const <Color>[Color(0xFF24242B), Color(0xFF5E607B), Color(0xFFC39D7E)],
    source: TrackSource.yandex,
    moods: const <String>['ночь', 'город', 'мечтать'],
    lyrics: _lyrics(const <String>[
      'окна пролетают мимо',
      'город уже уснул',
      'фонари считают секунды',
      'до следующей остановки',
      'ты смотришь наружу',
      'и думаешь ни о чём',
      'это тоже движение',
      'это тоже дом',
    ]),
  ),
  Track(
    id: 'quiet-room',
    title: 'Quiet Room',
    artist: 'Mori Tape',
    album: 'A Place To Breathe',
    assetPath: 'assets/audio/quiet_room.wav',
    duration: const Duration(seconds: 14),
    palette: const <Color>[Color(0xFF344039), Color(0xFF6E836F), Color(0xFFD6C8A8)],
    source: TrackSource.youtubeMusic,
    moods: const <String>['lo-fi', 'лес', 'выдохнуть'],
    lyrics: _lyrics(const <String>[
      'можно просто побыть',
      'без ответа',
      'без следующего шага',
      'звук дождя рядом',
      'лампа всё ещё горит',
      'чай давно остыл',
      'но музыка тёплая',
      'останься',
    ]),
  ),
  Track(
    id: 'warm-static',
    title: 'Warm Static',
    artist: 'Cassette Weather',
    album: 'Small Signals',
    assetPath: 'assets/audio/warm_static.wav',
    duration: const Duration(seconds: 14),
    palette: const <Color>[Color(0xFF5C5148), Color(0xFFA78D73), Color(0xFFE4C9A7)],
    source: TrackSource.gluk,
    moods: const <String>['кассета', 'уют', 'утро'],
    lyrics: _lyrics(const <String>[
      'маленький шум',
      'между нотами',
      'как старый магнитофон',
      'на кухне утром',
      'всё несовершенно',
      'и поэтому живое',
      'оставь как есть',
      'так лучше',
    ]),
  ),
];

const List<Playlist> demoPlaylists = <Playlist>[
  Playlist(
    id: 'slow-morning',
    name: 'Медленное утро',
    description: 'Собирать себя по нотам',
    trackIds: <String>['warm-static', 'soft-focus', 'weightless'],
  ),
  Playlist(
    id: 'after-midnight',
    name: 'После полуночи',
    description: 'Когда город засыпает',
    trackIds: <String>['night-bus', 'afterglow', 'quiet-room'],
  ),
  Playlist(
    id: 'deep-focus',
    name: 'Не отвлекаться',
    description: 'Тихий поток на фоне',
    trackIds: <String>['soft-focus', 'weightless', 'quiet-room'],
  ),
];

final Map<String, List<CommentEntry>> seedComments = <String, List<CommentEntry>>{
  'weightless': <CommentEntry>[
    CommentEntry(
      id: 'seed-1',
      author: 'mira',
      text: 'вот здесь идеально вступает фон',
      at: const Duration(seconds: 3),
      createdAt: DateTime(2026, 8, 14, 21, 7),
    ),
    CommentEntry(
      id: 'seed-2',
      author: 'nox',
      text: 'тот самый момент, когда можно выдохнуть',
      at: const Duration(seconds: 8),
      createdAt: DateTime(2026, 9, 2, 0, 42),
    ),
  ],
  'night-bus': <CommentEntry>[
    CommentEntry(
      id: 'seed-3',
      author: 'alina',
      text: 'реально ощущается как ночной автобус',
      at: const Duration(seconds: 5),
      createdAt: DateTime(2026, 9, 11, 23, 18),
    ),
  ],
};
